In [1]:
def AND(x1,x2):
    w1,w2,theta = 0.5,0.5,0.7
    tmp = x1*w1 + x2*w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1 

In [3]:
print(AND(0,0))
print(AND(1,0))
print(AND(0,1))
print(AND(1,1))

0
0
0
1


In [4]:
import numpy as np 
x = np.array([0,1])
w = np.array([0.5,0.5])
b = -0.7
print(w*x)
print(np.sum(w*x))
print(np.sum(w*x)+b)

[0.  0.5]
0.5
-0.19999999999999996


In [5]:
def AND(x1,x2):
    x = np.array([x1,x2])
    w = np.array([0.5,0.5])
    b = -0.7
    tmp = np.sum(w*x)+b
    if tmp <= 0:
        return 0 
    else:
        return 1 

In [6]:
print(AND(0,0))
print(AND(1,0))
print(AND(0,1))
print(AND(1,1))

0
0
0
1


In [7]:
def step_function(x):
    if x > 0:
        return 1 
    else:
        return 0

In [8]:
def step_function(x):
    y = x > 0 
    return y.astype(np.int)

In [18]:
x = np.array([-1.0,1.0,2.0])
x 

array([-1.,  1.,  2.])

In [19]:
y = x > 0 
y 

array([False,  True,  True])

In [21]:
y = y.astype(int)
y

array([0, 1, 1])